services:
  psql:
    image: postgres:latest
    environment:
      POSTGRES_DB: recruitment
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - /home/shaurya/code/data/postgresa:/var/lib/postgresql/data

volumes:
  psql_volume: